# Generated by Django 2.0.2 on 2020-07-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Body_text',
            new_name='body_text',
        ),
    ]
